apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hypriot
spec:
  rules:
  - host: 10.98.47.167
    http:
      paths:
      - path: /
        backend:
          serviceName: hypriot
          servicePort: 80