apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hypriotb
spec:
  rules:
  - host: hypriotb
    http:
      paths:
      - path: /
        backend:
          serviceName: hypriotb
          servicePort: 80