apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hypriotb
spec:
  rules:
  - http:
      paths:
      - path: /test
        backend:
          serviceName: hypriotb
          servicePort: 8090